number_1 = int(input("Enter number 1: "))
number_2 = int(input("Enter number 2: "))
print(f"{number_1} + {number_2} = {number_1+number_2}")
print(f"{number_1} - {number_2} = {number_1-number_2}")
print(f"{number_1} * {number_2} = {number_1*number_2}")
print(f"{number_1} / {number_2} = {number_1/number_2}")